# render.yaml
services:
  - type: web
    name: pdfkaro-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: pdfkaro-backend
          type: web
          property: url

  - type: web
    name: pdfkaro-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
